# https://cloud.google.com/kubernetes-engine/docs/how-to/configure-backend-service
apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
  name: backendconfig-svc2
  namespace: l7-ilb
spec:
  timeoutSec: 40
  connectionDraining:
    drainingTimeoutSec: 60
  sessionAffinity:
    affinityType: "CLIENT_IP"
---
apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
  namespace: l7-ilb
  name: backendconfig-svc3
spec:
  timeoutSec: 40
  connectionDraining:
    drainingTimeoutSec: 60
  sessionAffinity:
    affinityType: "GENERATED_COOKIE"
    affinityCookieTtlSec: 3600
